env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
  allowImportExportEverywhere: true
plugins:
  - svelte3
overrides:
  -
    files:
      - "*.svelte"
    processor: svelte3/svelte3
rules:
  semi:
    - error
    - never
  quotes:
    - error
    - double
  comma-spacing:
    - error
  comma-dangle:
    - error
    - never
  indent:
    - error
    - 2
  no-trailing-spaces:
    - error
    - skipBlankLines: true
  space-before-function-paren:
    - error
    - never
  no-var:
    - error
  prefer-const:
    - error
  arrow-spacing:
    - error
    - before: true
      after: true
  template-curly-spacing:
    - error
    - always
