env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
  allowImportExportEverywhere: true
extends:
  - "plugin:svelte/recommended"
overrides:
  -
    files:
      - "*.svelte"
    parser: svelte-eslint-parser
ignorePatterns:
  - /public
  - /**/zez-ui
rules:
  semi:
    - error
    - never
  quotes:
    - error
    - double
  comma-spacing:
    - error
  comma-dangle:
    - error
    - never
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-trailing-spaces:
    - error
  space-before-function-paren:
    - error
    - never
  no-var:
    - error
  prefer-const:
    - error
  arrow-spacing:
    - error
    - before: true
      after: true
  template-curly-spacing:
    - error
    - never
  svelte/no-at-html-tags:
    - off
  no-unused-vars:
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: true
      argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"
  no-whitespace-before-property:
    - error
  block-spacing:
    - error
  prefer-arrow-callback:
    - error
  prefer-spread:
    - error
  no-duplicate-imports:
    - error
  space-before-blocks:
    - error
  no-console:
    - warn
    - allow:
      - error
  space-infix-ops:
    - error
  no-multiple-empty-lines:
    - warn
    - max: 1
  svelte/no-dupe-on-directives:
    - error
  svelte/no-dupe-use-directives:
    - error
