global:
  guid: 000000007895
  en-US: Ongoing - Global
  es-MX: En curso - Global
  fr-FR: Toute la partie - Tout le monde
  ja-JP: 進行中 - グローバル
  pt-BR: Em andamento - Global
  zh-CN: 持续 - 全局
eachPlayer:
  guid: 000000007897
  en-US: Ongoing - Each Player
  es-MX: En curso - Cada jugador
  fr-FR: Toute la partie - Chaque joueur
  ja-JP: 進行中 - 各プレイヤー
  pt-BR: Em andamento - Cada Jogador
  zh-CN: 持续 - 每名玩家
playerTookDamage:
  guid: 00000000B313
  en-US: Player Took Damage
  es-MX: El jugador recibió daño
  fr-FR: Un joueur subit des dégâts
  ja-JP: プレイヤーがダメージを受けた
  pt-BR: Jogador Recebeu Dano
  ru-RU: Player took damage
  zh-CN: 玩家受到伤害
playerDealtDamage:
  guid: 00000000B52D
  en-US: Player Dealt Damage
  es-MX: El jugador infligió daño
  fr-FR: Un joueur inflige des dégâts
  ja-JP: プレイヤーがダメージを与えた
  pt-BR: Jogador Causou Dano
  ru-RU: Player dealt damage
  zh-CN: 玩家造成伤害
playerDealtFinalBlow:
  guid: 0000000078F8
  en-US: Player Dealt Final Blow
  es-MX: El jugador asestó un golpe de gracia
  fr-FR: Un joueur inflige un coup de grâce
  ja-JP: ファイナル・ブロウを獲得
  pt-BR: Jogador Desferiu Golpe Final
  ru-RU: Player dealt final blow
  zh-CN: 玩家造成最后一击
playerDied:
  guid: 00000000B314
  en-US: Player Died
  es-MX: El jugador murió
  fr-FR: Un joueur meurt
  ja-JP: プレイヤーが倒れた
  pt-BR: Jogador morreu
  zh-CN: 玩家阵亡
playerEarnedElimination:
  guid: 0000000078F7
  en-US: Player Earned Elimination
  es-MX: El jugador obtuvo una eliminación
  fr-FR: Un joueur obtient une élimination
  ja-JP: プレイヤーがキルを獲得
  pt-BR: Jogador Conseguiu Eliminação
  ru-RU: Player earned elimination
  zh-CN: 玩家参与消灭
playerDealtHealing:
  guid: 00000000CC16
  en-US: Player Dealt Healing
  es-MX: El jugador realizó una sanación
  fr-FR: Un joueur a prodigué des soins
  ja-JP: プレイヤーが回復を与えた
  pt-BR: Jogador Realizou Cura
  zh-CN: 玩家造成治疗
playerReceivedHealing:
  guid: 00000000CC17
  en-US: Player Received Healing
  es-MX: El jugador recibió una sanación
  fr-FR: Un joueur a reçu des soins
  ja-JP: プレイヤーが回復を受けた
  pt-BR: Jogador Recebeu Cura
  zh-CN: 玩家受到治疗
playerJoined:
  guid: 00000000CC18
  en-US: Player Joined Match
  es-MX: El jugador se unió a la partida
  fr-FR: Un joueur a rejoint la partie
  ja-JP: プレイヤーがマッチに参加
  pt-BR: Jogador Entrou na Partida
  zh-CN: 玩家加入比赛
playerLeft:
  guid: 00000000CC19
  en-US: Player Left Match
  es-MX: El jugador abandonó la partida
  fr-FR: Un joueur a quitté la partie
  ja-JP: プレイヤーがマッチから離脱
  pt-BR: Jogador Saiu da Partida
  zh-CN: 玩家离开比赛
__subroutine__:
  guid: 00000000FFF6
  en-US: Subroutine
  es-ES: Subrutina
  es-MX: Subrutina
  fr-FR: Sous-programme
  ja-JP: サブルーチン
  pt-BR: Sub-rotina
  zh-CN: 子程序
playerDealtKnockback:
  guid: 0000000105BB
  en-US: Player Dealt Knockback
  es-ES: Repulsión infligida por el jugador
  es-MX: El jugador infligió un derribo
  fr-FR: Un joueur a infligé un recul
  ja-JP: プレイヤーがノックバックを与えた
  pt-BR: Jogador Causou Repulsão
  zh-CN: 玩家造成击退
playerReceivedKnockback:
  guid: 0000000105BC
  en-US: Player Received Knockback
  es-ES: Repulsión sufrida por el jugador
  es-MX: El jugador recibió un derribo
  fr-FR: Un joueur a reçu un recul
  ja-JP: プレイヤーがノックバックを受けた
  pt-BR: Jogador Recebeu Repulsão
  zh-CN: 玩家受到击退
