global:
  en-US: Ongoing - Global
eachPlayer:
  en-US: Ongoing - Each Player
playerTookDamage:
  en-US: Player Took Damage
playerDealtDamage:
  en-US: Player Dealt Damage
playerDealtFinalBlow:
  en-US: Player Dealt Final Blow
playerDied:
  en-US: Player Died
playerEarnedElimination:
  en-US: Player Earned Elimination
playerDealtHealing:
  en-US: Player Dealt Healing
playerReceivedHealing:
  en-US: Player Received Healing
playerJoined:
  en-US: Player Joined Match
playerLeft:
  en-US: Player Left Match
__subroutine__:
  en-US: Subroutine
  es-ES: Subrutina
playerDealtKnockback:
  en-US: Player Dealt Knockback
  es-ES: Repulsión infligida por el jugador
playerReceivedKnockback:
  en-US: Player Received Knockback
  es-ES: Repulsión sufrida por el jugador
