# Abilities and passives
- A-36 Tactical Grenade
- Accretion
- Adaptive Shield
- Adrenaline Rush
- Amp It Up
- Amplification Matrix
- Anchor
- Angelic Descent
- Annihilation
- Armor Pack
- Attack Speed
- Attack
- Augmented Fusion Driver
- Axe Recall
- Barbed Axe
- Barrage
- Barrier Field
- Barrier Projector
- Barrier Shield
- Berserker
- Biotic Field
- Biotic Grasp Alt Fire
- Biotic Grasp
- Biotic Grenade
- Biotic Launcher Alt Fire
- Biotic Launcher
- Biotic Orb
- Biotic Rifle
- Blink
- Blizzard
- Block (Nemesis Form)
- Bob
- Bonespur
- Boosters
- Build Turret
- Burrow
- Caduceus Blaster
- Caduceus Staff
- Cage Fight
- Call Mech
- Captive Sun
- Cardiac Overdrive
- Carnage
- Catch
- Chain Hook
- Charge
- Clobber
- Coach Gun
- Coalescence
- Combat Roll
- Commanding Shout
- Concussion Mine
- Concussive Blast
- "Configuration: Artillery"
- "Configuration: Assault"
- "Configuration: Recon"
- "Configuration: Tank"
- Crossfade
- Cryo Freeze
- Cyber Agility
- Deadeye
- Death Blossom
- Defense Matrix
- Deflect
- Deploy Turret
- Dire Grenade
- Disruptor Shot
- Divine Assault
- Divine Power
- Downpour
- Dragonblade
- Dragonstrike
- Drill Dash
- Duplicate
- Dynamite
- Earthshatter
- Eject
- Emp
- Endothermic Blaster
- Energy Javelin
- Energy
- Exo Boots
- Experimental Barrier
- Explorers Resolve
- Fade
- Fan of Blades
- Fire Strike
- Flashbang
- Flight
- Flurry
- Focusing Beam
- Forge Hammer
- Fortify
- Frag Launcher
- Fusion Cannons
- Fusion Driver
- Glide
- Glide Boost
- Grappling Claw
- Grappling Hook
- Gravitic Flux
- Graviton Surge
- Guardian Angel
- Hack
- Halt
- Hand Cannon
- Healing Blossom
- Healing Boost
- Healing Ofuda
- Healing Pylon
- Health
- Heavy Pulse Rifle
- Helix Rockets
- Hellfire Desire
- Hellfire Shotguns
- Hover Jets
- Hyper Ring
- Hyperspheres
- Ice Wall
- Icicle
- Immortality Field
- Incendiary Chaingun
- Infra Sight
- Inspire
- Ironclad
- Jagged Blade
- Jagged Wall
- Javelin Spin
- Jet Dash
- Jump Jet
- Jump Pack
- Kinetic Grasp
- Kitsune Rush
- Kunai
- Life Grip
- Light Gun
- Lunge
- Machine Pistol
- Magnetic Grenade
- Martian Overboots
- Mediblaster
- Melee Bump
- Meteor Strike
- Micro Missiles
- Minefield
- "Modifier: Death From Above"
- Molten Core
- Movement Speed
- Nano Boost
- Nemesis Form
- Nimble Feet
- Opportunist
- Orb of Destruction
- Orb of Discord
- Orb of Harmony
- Orbital Ray
- Outburst
- Overclock
- Overload
- Overrun
- Particle Barrier
- Particle Cannon
- Passive
- Peacekeeper
- Petal Platform
- Photon Barrier
- Photon Barrier (Original)
- Photon Projector
- Photon Shield
- Pig Pen
- Piledriver
- Power Block
- Power Slide
- Primal Rage
- Projected Barrier
- Protection Suzu
- Pulsar Torpedoes
- Pulse Bomb
- Pulse Pistols
- Pummel (Nemesis Form)
- Punch
- Quad Cannons
- Quick Melee
- Railgun Alt Fire
- Railgun
- Rally
- Rampage
- Ravenous Vortex
- Recall
- Reconfigure
- Regenerative Burst
- Rejuvenating Dash
- Repair Pack
- Resurrect
- Rip Tire
- Rising Uppercut
- Rivet Gun Alt Fire
- Rivet Gun
- Rocket Flail
- Rocket Hammer
- Rocket Launcher
- Rocket Punch
- Role Damage
- Role Support
- Role Tank
- Roll
- Rune of Disguise
- Scampy Stun
- Scatter Arrow
- Scattergun
- Scrap Gun
- Seismic Slam
- Self Destruct
- Self Repair
- Sentry Turret
- Shadow Step
- Shield Bash
- Shield Generator
- Shockwave
- Shuriken
- Sleep Dart
- Smart Excavator
- Snap Kick
- Snowball Blaster
- Solar Rifle
- Solar Rifle Alt
- Sonic Amplifier
- Sonic Arrow
- Soulbind
- Sound Barrier
- Soundwave
- Spike Guard
- Sprint
- Stealth
- Steel Trap
- Sticky Bombs
- Storm Arrows
- Storm Bow
- Strike
- Supercharger
- Swift Step
- Swift Strike
- Sympathetic Recovery
- Tactical Visor
- Take a Breather
- Tectonic Shock
- Teleporter
- Terra Surge
- Tesla Cannon
- Thaw
- The Best Defense
- The Reaping
- The Viper
- Thorn Volley
- Total Mayhem
- Transcendence
- Translocator
- Tree of Life
- Tri Shot
- Turbo Boost
- Ultimate Play
- Valkyrie
- Vault
- Venom Mine
- Violent Leap
- Virus
- Volatile Chaingun
- Void Accelerator (Omnic Form)
- Void Barrier (Omnic Form)
- Wall Climb
- Wall Ride
- Wall Slam
- Whip Shot
- Whole Hog
- Widows Kiss
- Wraith Form
- Yeti Trap

# Perks
- Accelerando
- Acrobatics
- Adhesive Siphon
- Advanced Teleportation
- Agility Training
- Airburst
- Aluminium Frame
- Anarchic Zeal
- Anchor Bolts
- Angelic Recovery
- Armored Artillery
- Ascendance
- Assault Burst
- Automated Healing
- Bang Bang
- Barrier Restoration
- Bass Blowout
- Battle Shout
- Biotic Bounce
- Biting Cold
- Blade Twisting
- Blast from the Past
- Blink Packs
- Bunny Stomp
- Chain Boost
- Chain Lightning
- Charged Javelin
- Chilling Reach
- Cleansing Grasp
- Combat Fuel
- Concussive Implosion
- Contamination
- Covered In Dirt
- Craftsman
- Crusader's Resolve
- Crushing Victory
- Cryo-Storm
- CTRL ALT ESC
- Deadly Deux
- Death's Shadow
- Deep Leap
- Deep Wounds
- Dire Triggers
- Dragon Fury
- Dragon's Thirst
- Drift Thrusters
- Dual Thrusters
- Duality
- Ejection Suit
- Energy Lance
- Enhanced Duplication
- Escape Plan
- Ethical Nourishment
- Excavation Exhilaration
- Extended Mag
- Familiar Vitals
- Field Emergency
- Field Medicine
- Fiery Uptake
- Firewalker
- Flash Heal
- Flashback
- Fleeting Bulwark
- Focused Aim
- Focused Destruction
- Fortune Teller
- Foxtrot
- Frag Cannon
- Friendly Imaging
- Fuel Stores
- Full Salvo
- Fully Loaded
- Graviton Crush
- Groggy
- Groovin'
- Gun Slingin'
- Hang Time
- Headhunter
- Heat Dissipator
- Heavy Landing
- Heavy Rockets
- Helix Shields
- High Beams
- Hog Toss
- Hogdrogen Exposure
- Hyper Boost
- Hyper Strike
- Invigorate
- Jump-Ups
- Kinetic Bandolier
- Kinetic Cycle
- Levitation
- Life Cycle
- Lifeweaving
- Lindholm Explosives
- Massive Impact
- Master Blaster
- Meditation
- Morale Boost
- Nitro Boost
- Noise Violation
- Off the Top
- One-Two
- Overcharged
- Overloaded Turret
- Pack Rat
- Past Noon
- Perfect Alignment
- Permafrost
- Power Matrix
- Protective Barrier
- Quantum Entanglement
- Quick Draw
- Quick Fix
- Rapid Construction
- Rapid Fire
- Ravenous Wraith
- Reconstitution
- Recycled Pulse Munitions
- Rending Recall
- Revitalizing Barrier
- Re-Boots
- Rocket Boots
- Savage Satiation
- Scatter Arrows
- Scoped Efficiency
- Scrap Hook
- Seismic Empowerment
- Seismic Sense
- Self-Repair
- Sentry Capacity
- Shield Battery
- Shield Slam
- Shield System
- Short Circuit
- Shrike
- Shuffling
- Sidewinder
- Smart Bomb
- SMART-R Excavator
- Solar Power
- Sonic Disruption
- Soul Reaving
- Spotter
- Stack Overflow
- Steamroller
- Stim Pack
- Summer Solstice
- Sunburn
- Superbloom
- Survival of the Fittest
- Tick Tock
- Transfer Efficiency
- Two Hearts
- Uprush
- Urgent Care
- Vanish
- Viper's Sting
- Viral Efficacy
- Whiplash
- White Hat
- Winged Reach
- Yamagami Technique
- Zenith Kick
