-
  alt: Check out Exclusives at Blizzard Gear Fest!
  lg:
    id: 930176
    url: https://blizzardgearstore.l49yho.net/c/2456162/930176/10799
    img: //a.impactradius-go.com/display-ad/10799-930176
  md:
    id: 930175
    url: https://blizzardgearstore.l49yho.net/c/2456162/930175/10799
    img: //a.impactradius-go.com/display-ad/10799-930175
  sm:
    id: 930172
    url: https://blizzardgearstore.l49yho.net/c/2456162/930172/10799
    img: //a.impactradius-go.com/display-ad/10799-930172
  xs:
    id: 930169
    url: https://blizzardgearstore.l49yho.net/c/2456162/930169/10799
    img: //a.impactradius-go.com/display-ad/10799-930169
-
  alt: Check out Exclusives at Blizzard Gear Fest!
  lg:
    id: 921762
    url: https://blizzardgearstore.l49yho.net/c/2456162/921762/10799
    img: //a.impactradius-go.com/display-ad/10799-921762
  md:
    id: 921759
    url: https://blizzardgearstore.l49yho.net/c/2456162/921759/10799
    img: //a.impactradius-go.com/display-ad/10799-921759
  sm:
    id: 921753
    url: https://blizzardgearstore.l49yho.net/c/2456162/921753/10799
    img: //a.impactradius-go.com/display-ad/10799-921753
  xs:
    id: 921746
    url: https://blizzardgearstore.l49yho.net/c/2456162/921746/10799
    img: //a.impactradius-go.com/display-ad/10799-921746
-
  alt: Shadowlands Thrall Statue at Blizzard Gear Store
  lg:
    id: 915762
    url: https://blizzardgearstore.l49yho.net/c/2456162/915762/10799
    img: //a.impactradius-go.com/display-ad/10799-915762
  md:
    id: 915761
    url: https://blizzardgearstore.l49yho.net/c/2456162/915761/10799
    img: //a.impactradius-go.com/display-ad/10799-915761
  sm:
    id: 915758
    url: https://blizzardgearstore.l49yho.net/c/2456162/915758/10799
    img: //a.impactradius-go.com/display-ad/10799-915758
  xs:
    id: 915755
    url: https://blizzardgearstore.l49yho.net/c/2456162/915755/10799
    img: //a.impactradius-go.com/display-ad/10799-915755
-
  alt: Check out Exclusives at Blizzard Gear Fest!
  lg:
    id: 932978
    url: https://blizzardgearstore.l49yho.net/c/2456162/932978/10799
    img: //a.impactradius-go.com/display-ad/10799-932978
  md:
    id: 932977
    url: https://blizzardgearstore.l49yho.net/c/2456162/932977/10799
    img: //a.impactradius-go.com/display-ad/10799-932977
  sm:
    id: 932970
    url: https://blizzardgearstore.l49yho.net/c/2456162/932970/10799
    img: //a.impactradius-go.com/display-ad/10799-932970
  xs:
    id: 932958
    url: https://blizzardgearstore.l49yho.net/c/2456162/932958/10799
    img: //a.impactradius-go.com/display-ad/10799-932958
-
  alt: Check out Exclusives at Blizzard Gear Fest!
  lg:
    id: 932919
    url: https://blizzardgearstore.l49yho.net/c/2456162/932919/10799
    img: //a.impactradius-go.com/display-ad/10799-932919
  md:
    id: 932906
    url: https://blizzardgearstore.l49yho.net/c/2456162/932906/10799
    img: //a.impactradius-go.com/display-ad/10799-932906
  sm:
    id: 932898
    url: https://blizzardgearstore.l49yho.net/c/2456162/932898/10799
    img: //a.impactradius-go.com/display-ad/10799-932898
  xs:
    id: 932883
    url: https://blizzardgearstore.l49yho.net/c/2456162/932883/10799
    img: //a.impactradius-go.com/display-ad/10799-932883
