- Free for all
- Team Deathmatch
- Solo
- Elimination
- 1vs1
- King of the Hill
- Boss Mode
- Minigames
- Parkour
- Survival
- Protect
- Hide and Seek
- PvE
- Practice Mode
- Hero Adjustments
- New Heroes
- Miscellaneous
