-
  id: 1
  name: Free for all
-
  id: 2
  name: Team Deathmatch
-
  id: 3
  name: Solo
-
  id: 4
  name: Elimination
-
  id: 5
  name: 1vs1
-
  id: 6
  name: King of the Hill
-
  id: 7
  name: Boss Mode
-
  id: 8
  name: Minigames
-
  id: 9
  name: Parkour
-
  id: 10
  name: Survival
-
  id: 11
  name: Protect
-
  id: 12
  name: Hide and Seek
-
  id: 13
  name: PvE
-
  id: 14
  name: Hero Adjustments
-
  id: 15
  name: New Heroes
-
  id: 16
  name: Miscellaneous
