-
  en: D.va
  ko: D.va
  category: Tank
-
  en: Orisa
  ko: 오리사
  category: Tank
-
  en: Reinhardt
  ko: 라인하르트
  category: Tank
-
  en: Roadhog
  ko: 로드호그
  category: Tank
-
  en: Sigma
  ko: 시그마
  category: Tank
-
  en: Winston
  ko: 윈스턴
  category: Tank
-
  en: Wrecking Ball
  ko: 레킹볼
  category: Tank
-
  en: Zarya
  ko: 자리야
  category: Tank
-
  en: Ashe
  ko: 애쉬
  category: Damage
-
  en: Bastion
  ko: 바스티온
  category: Damage
-
  en: Doomfist
  ko: 둠피스트
  category: Damage
-
  en: Echo
  ko: 에코
  category: Damage
-
  en: Genji
  ko: 겐지
  category: Damage
-
  en: Hanzo
  ko: 한조
  category: Damage
-
  en: Junkrat
  ko: 정크랫
  category: Damage
-
  en: McCree
  ko: 맥크리
  category: Damage
-
  en: Mei
  ko: 메이
  category: Damage
-
  en: Pharah
  ko: 파라
  category: Damage
-
  en: Reaper
  ko: 리퍼
  category: Damage
-
  en: "Soldier: 76"
  ko: "솔저: 76"
  category: Damage
-
  en: Sombra
  ko: 솜브라
  category: Damage
-
  en: Symmetra
  ko: 시메트라
  category: Damage
-
  en: Torbjörn
  ko: 토르비욘
  category: Damage
-
  en: Tracer
  ko: 트레이서
  category: Damage
-
  en: Widowmaker
  ko: 위도우메이커
  category: Damage
-
  en: Ana
  ko: 아나
  category: Support
-
  en: Baptiste
  ko: 바티스트
  category: Support
-
  en: Brigitte
  ko: 브리기테
  category: Support
-
  en: Lúcio
  ko: 루시우
  category: Support
-
  en: Mercy
  ko: 메르시
  category: Support
-
  en: Moira
  ko: 모이라
  category: Support
-
  en: Zenyatta
  ko: 젠야타
  category: Support
