-
  en: Hanamura
  ko: 하나무라
  type: Assault
  slug: hanamura
-
  en: Horizon Lunar Colony
  ko: 호라이즌 달 기지
  type: Assault
  slug: horizon-lunar-colony
-
  en: Paris
  ko: 파리
  type: Assault
  slug: paris
-
  en: Temple of Anubis
  ko:  아누비스 신전
  type: Assault
  slug: temple-of-anubis
-
  en: Volskaya Industries
  ko: 볼스카야 인더스트리
  type: Assault
  slug: volskaya-industries
-
  en: Dorado
  ko: 도라도
  type: Escort
  slug: dorado
-
  en: Havana
  ko: 하바나
  type: Escort
  slug: havana
-
  en: Junkertown
  ko: 쓰레기촌
  type: Escort
  slug: junkertown
-
  en: Rialto
  ko: 리알토
  type: Escort
  slug: rialto
-
  en: Route 66
  ko: 66번 국도
  type: Escort
  slug: route-66
-
  en: "Watchpoint: Gibraltar"
  ko: "감시 기지: 지브롤터"
  type: Escort
  slug: watchpoint-gibraltar
-
  en: Blizzard World
  ko: 블리자드 월드
  type: Hybrid
  slug: blizzard-world
-
  en: Eichenwalde
  ko: 아이헨발데
  type: Hybrid
  slug: eichenwalde
-
  en: Hollywood
  ko: 할리우드
  type: Hybrid
  slug: hollywood
-
  en: King's Row
  ko:  왕의 길
  type: Hybrid
  slug: kings-row
-
  en: Numbani
  ko: 눔바니
  type: Hybrid
  slug: numbani
-
  en: Busan
  ko: 부산
  type: Control
  slug: busan
-
  en: Ilios
  ko: 일리오스
  type: Control
  slug: ilios
-
  en: Lijiang Tower
  ko: 리장 타워
  type: Control
  slug: lijiang-tower
-
  en: Nepal
  ko: 네팔
  type: Control
  slug: nepal
-
  en: Oasis
  ko: 오아시스
  type: Control
  slug: oasis
-
  en: Black Forest
  ko: 검은 숲
  type: Arcade
  slug: black-forest
-
  en: Castillo
  ko: 카스티요
  type: Arcade
  slug: castillo
-
  en: "Ecopoint: Antarctica"
  ko: "탐사 기지: 남극"
  type: Arcade
  slug: ecopoint-antarctica
-
  en: Necropolis
  ko: 네크로폴리스
  type: Arcade
  slug: necropolis
-
  en: Estádio das Rãs
  ko: 이스타지우 다스 하스
  type: Lúcioball
  slug: estadio-das-ras
-
  en: Sydney Harbour Arena
  ko: 시드니 하버 아레나
  type: Lúcioball
  slug: sydney-harbour-arena
-
  en: Sydney Harbour Arena Classic
  ko: 시드니 하버 아레나 클래식
  type: Lúcioball
  slug: sydney-harbour-arena-classic
-
  en: Busan Stadium
  ko: 부산 스타디움
  type: Lúcioball
  slug: busan-stadium
-
  en: Busan Stadium Classic
  ko: 부산 스타디움 클래식
  type: Lúcioball
  slug: busan-stadium-classic
-
  en: Château Guillard
  ko: 샤토 기야르
  type: Deathmatch
  slug: chateau-guillard
-
  en: Petra
  ko: 페트라
  type: Deathmatch
  slug: petra
-
  en: Ayutthaya
  ko: 아유타야
  type: Capture the Flag
  slug: ayutthaya
-
  en: Practice Range
  ko: 훈련장
  type: Practice
  slug: practice-range
-
  en: Workshop Chamber
  ko: 워크샵 방
  type: Workshop
  slug: workshop-chamber
-
  en: Workshop Island
  ko: 워크샵 섬
  type: Workshop
  slug: workshop-island
-
  en: Workshop Expanse
  ko: 워크샵 개활지
  type: Workshop
  slug: workshop-expanse
-
  en: Workshop Green Screen
  ko: 워크샵 초록색 화면
  type: Workshop
  slug: workshop-green-screen
