-
  quote: How... Disappointing.
  by: Tekhartha Zenyatta
-
  quote: Existence is mysterious.
  by: Tekhartha Zenyatta
-
  quote: Sorry! Sorry, I'm sorry. Sorry.
  by: Mei-Ling Zhou
-
  quote: I tried my best.
  by: Mei-Ling Zhou
-
  quote: I'm sure there is a reasonable scientific explanation for this.
  by: Mei-Ling Zhou
-
  quote: I was only trying to help.
  by: Mei-Ling Zhou
-
  quote: Ooh, sorry about that.
  by: Mei-Ling Zhou
-
  quote: Aw, rubbish!
  by: Lena Oxton
-
  quote: Guh-- no way.
  by: Hana Song
-
  quote: How embarrassing!
  by: Winston
-
  quote: Houston, uhh, we have a problem.
  by: Winston
