name: CI
on: [push, pull_request]
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - run: yarn install
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: ESLint
        run: |
          yarn run eslint app/javascript
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - run: yarn install
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Precompile assets
        run: |
          bundle exec rails webpacker:compile RAILS_ENV=test
      - name: Test
        run: |
          rake db:test:prepare
          rails test
      - name: RSpec
        run: |
          bundle exec rspec
  features:
    name: Cucumber Feature Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
          sudo apt-get install firefox-geckodriver
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - run: yarn install
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Precompile assets
        run: |
          bundle exec rails webpacker:compile RAILS_ENV=test
      - name: Cucumber
        run: |
          rake db:test:prepare
          bundle exec cucumber
