name: CI
on: [push, pull_request]
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - run: yarn install
      - name: ESLint
        run: |
          yarn run eslint app/javascript
  test:
    runs-on: ubuntu-latest
    environment: CI
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      RAILS_CREDENTIALS: ${{ secrets.RAILS_CREDENTIALS }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
          sudo rm config/credentials.yml.enc
          echo "$RAILS_CREDENTIALS" > config/credentials.yml.enc
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
          cache: 'yarn'
      - run: yarn install
      - name: Precompile assets
        run: |
          bundle exec rails webpacker:compile RAILS_ENV=test
      - name: Test
        run: |
          bundle exec rake db:test:prepare
          bundle exec rails test
      - name: RSpec
        run: |
          bundle exec rspec
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        with:
          limit-access-to-actor: true
  features:
    name: Cucumber Feature Check
    runs-on: ubuntu-latest
    environment: CI
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      RAILS_CREDENTIALS: ${{ secrets.RAILS_CREDENTIALS }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
          sudo apt-get install firefox-geckodriver
          sudo rm config/credentials.yml.enc
          echo "$RAILS_CREDENTIALS" > config/credentials.yml.enc
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
          cache: 'yarn'
      - run: yarn install
      - name: Precompile assets
        run: |
          bundle exec rails webpacker:compile RAILS_ENV=test
      - name: Cucumber
        run: |
          bundle exec rake db:test:prepare
          bundle exec cucumber
