name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup System
        run: |
          sudo apt update
          sudo apt-get install libsqlite3-dev
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
      - name: Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Bundle
        run: |
          gem uninstall -aIx bundler
          gem install bundler
          bundle install --without production development --jobs 4 --retry 3
      - name: Test
        run: |
          rails db:migrate RAILS_ENV=test
          rails test
      - name: RSpec
        run: |
          bundle exec rspec
